server:
  port: 12741

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:mappers/*Mapper.xml

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    name: sv
    url: jdbc:mysql://ip/quartz?useUnicode=true&characterEncoding=utf8
    username: root
    password: 7d428bc667
    type: com.alibaba.druid.pool.DruidDataSource



